#include<stdlib.h>
#include<time.h>
#include<string.h>
#include<stdio.h>
#include<conio.h>
#include<math.h>
int main (int argc, char *argv[])
{
unsigned int iseed = (unsigned int)time(NULL);
int i,k,j,die[2],n[100],c,flag=0;
long int amt[100];
unsigned int sum=0;
long int sum1=0;
char str[100][20];
FILE*fp;
clrscr();
fp=fopen("casinok.dat","wb+");
textcolor(WHITE);
gotoxy(28,10);
cprintf("\n\nWELCOME TO CASINO WORLD\n\n");
textcolor(YELLOW);
gotoxy(30,20);
cprintf("\nARE YOU READY?\n\n");
textcolor(GREEN);
gotoxy(30,25);
cprintf("\n1.YES\n");
textcolor(RED);
gotoxy(30,30);
cprintf("\n2.NO\n");
textcolor(YELLOW);
gotoxy(30,35);
cprintf("\nEnter your choice: ");

scanf("%d",&c);
if(c == 2)
	{
	clrscr();
	textcolor(RED);
	gotoxy(30,25);
	cprintf("exiting game.....");
	getch();
	}
if(c == 1)
	{
		clrscr();
		textcolor(RED);
		gotoxy(30,25);
		cprintf("\nloading game.....\n");
		getch();
		clrscr();
srand (iseed);
	 for(i=0;i<2;i++)
		{
		die[i+1]=rand()%6+1;
		sum =sum+die[i+1];
		}
		gotoxy(25,25);
		cprintf("enter no of players:");
		scanf("%d",&j);
		for(k=0;k<j;k++)
			{
			fseek(fp,0,SEEK_END);
				clrscr();
				textcolor(CYAN);
				gotoxy(25,15);
				cprintf("enter the detail of player:%d",k+1);
				fwrite(str,100,1,fp);
				textcolor(LIGHTGREEN);
				gotoxy(25,20);
				cprintf("\n1.enter your name: ");
				scanf("\n%s",&str[k+1]);
				fwrite(amt,100,1,fp);
				gotoxy(25,25);
				cprintf("\n2.enter the amount you wish to bet: Rs.");
				scanf("\n%ld",&amt[k+1]);
				fwrite(n,100,1,fp);
				gotoxy(25,30);
				cprintf("\n3.enter the number selected by you: ");
				scanf("%d",&n[k+1]);
				sum1 = sum1+amt[k+1];

			}
			clrscr();
		textcolor(MAGENTA);
		gotoxy(25,20);
		cprintf("random variable generated by computer = %d\n",sum);
	       for(k=0;k<j;k++)
			{
				if(n[k+1] == sum)
				{
				flag++;
				}
			}
			if(flag==1)
			{textcolor(CYAN);
				gotoxy(30,30);
				cprintf("%s won...!!!", str[k+1]);
				textcolor(CYAN);
				gotoxy(30,30);
				cprintf("\nthe amount won is Rs.%ld",sum1);
				}
			if(flag==0)
			{
			textcolor(CYAN);
			gotoxy(30,30);
			cprintf("\n\nyou all lost...!!");
			}
			if (flag>1)
			{
			textcolor(CYAN);
			gotoxy(30,30);
			cprintf("\ntwo users enter same number\n");
			}
	}

return 0;
fclose(fp);
}
